export enum ActionNames {
  // Product list actions
  RECEIVED_DATA = 'RECEIVED_DATA',
  RECEIVED_DATA_ERROR = 'RECEIVED_DATA_ERROR',
  INCREASE_AMOUNT_IN_STOCK = 'INCREASE_AMOUNT_IN_STOCK',
  DECREASE_AMOUNT_IN_STOCK = 'DECREASE_AMOUNT_IN_STOCK',
  // Product details actions
  GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID',
  GET_PRODUCT_BY_ID_ERROR = 'GET_PRODUCT_BY_ID_ERROR',
  GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS',
  RESET_SELECTED_PRODUCT = 'RESET_SELECTED_PRODUCT',
  // Checkout actions
  REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART',
  INCREASE_AMOUNT = 'INCREASE_AMOUNT',
  DESCRESE_AMOUNT = 'DECREASE_AMOUNT',
  ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART',
  // Loader actions
  ENABLE_LOADER = 'ENABLE_LOADER',
  DISABLE_LOADER = 'DISABLE_LOADER',
}
