export enum ActionNames {
  // Product list actions
  RECEIVED_DATA = 'RECEIVED_DATA',
  // Product details actions
  GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID',
  RESET_SELECTED_PRODUCT = 'RESET_SELECTED_PRODUCT',
  // Checkout actions
  REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART',
  UPDATE_ITEM_QUANTITY = 'UPDATE_ITEM_QUANTITY',
  ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART',
  // Loader actions
  ENABLE_LOADER = 'ENABLE_LOADER',
  DISABLE_LOADER = 'DISABLE_LOADER',
}
